language: rust
env:
  global:
    - PROJECT_NAME: finalfrontier
matrix:
  fast_finish: true
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: 1.31.0
    - os: linux
      rust: nightly
  allow_failures:
  - rust: nightly
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo test
before_deploy: ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: xnZPmJSADTRlfTm4G2u5182tJwqTr0SziIUPZ4uFg7Hfowf0LwwzJSt+Va4gBslEzxbdb/iT3cDXQpiKnOCcwLbtX+SqE6PsO3C66NYL1ff1VghKn8gNdPD9kERXydc6exAxGQ8tB81tOreXXuYC2X2nuqFDmwE5hsTjifg2gDrFjQwFcgcmnmRYgw6SwSeBb4JllFAr5kKLRafqznuvX39eIkxGqXc1EtRIA2M2wZWqVPcgolKut0KPm7RjuCWc8kgAG1Co5/kjtcG4uTSoz8HNTKfZRNM2IemQDUZr2BND2MYj/DC626JZHFXnjV/4+pTByI3iigZV+EuLNThZzepbomL3Y0ITVgrycbExwncITjkXTqSQrubx2C8ZmRQgPIWufDXgIaPLHx2BgF1r0Tya14ST8YMkCRQkfwAMiuIdwVZXATYM2BRAQi1RCfIhPQrTuWWRFSrZChhBNFMu8vUB4NB3szDLGr8/WOINIr2f7T/4/Q7fFbsEnAVDJCEdpvuwj7qTvXB11V4OQO9n28DCRyPwxHNjThgwcIEd1tZPtRYOMX1wHxeTzo1rpSNgqvRtfKvIL+ICTJN9Dp3yyKe5e8UAGFT7FEKsvjaSKOo3/8qHVKd0oCtqy+Uhyf07GnjP95BolgfAxwqI6bVKMFm/YZxRELlPOafXS0799Vg=
  file_glob: true
  file: deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    repo: finalfusion/finalfrontier
    tags: true
